# Welcome to Jekyll!
#

# Site settings
title: Kopi
description: Coffee Delivered Daily
owner: Kopi
first_published: 2017 # if migrating another site, the year of your first publish
email: contact@kopi.cafe
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.kopi.cafe" # the base hostname & protocol for your site
permalink: pretty
social:
  facebook-official: https://facebook.com/kopimtl
  instagram: https://www.instagram.com/kopimtl
  twitter: https://twitter.com/kopimtl
  #amazon:
  #angellist:
  #bitbucket-square:
  #connectdevelop:
  #delicious:
  #deviantart:
  #digg:
  #email: contact@kopi.cafe
  #flickr:
  #forumbee:
  #foursquare:
  #github: https://github.com/kopi
  #google-plus-square: https://plus.google.com/100188583768021555737
  #ils:
  #leanpub:
  #linkedin-square: https://www.linkedin.com/company/kopimtl
  #linux:
  #pied-piper:
  #reddit:
  #skyatlas:
  #slack: https://kopimtl.slack.com
  #soundcloud:
  #spotify:
  #stackexchange:
  #stack-overflow:
  #stubleupon:
  #trello:
  #tripadvisor:
  #tumblr-square:
  #vimeo:
  #vine:
  #vk:
  #weibo:
  #weixin:
  #yelp:
  #youtube-square:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
